# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coindesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='coindesk.Article'),
        ),
    ]
