# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coindesk', '0003_auto_20170621_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='handle',
        ),
    ]
